# the @ operator is very important
# we can suppress some command with it. So it won't appear on our terminal

all: say_hello create_files

say_hello:
	@echo "Hello There!"

create_files:
	@echo "Hello there, again" >> hello.txt
	@touch empty-file.txt

clean: 
	@rm *.txt
