# the default target is usually called 'all' and it calls the others targets

all: say_hello generate 

say_hello:
	@echo "Hello there!"

generate:
	@echo "Creating files..."
	@touch file-test.txt

clean:
	@echo "Cleaning up"
	@rm *.txt